#!/bin/sh
# WWW          : https://github.com/wwwsensor/pmcp
# Author       : @sensor @ss
# Dependencies : fzf portablemc
#
# portablemc extension
pmcp(){

## COMMON VARS ###############
N=/dev/null
DIR=~/.local/share/portablemc

CONFIG=$DIR/config
LOGS=$DIR/logs
MODS=$DIR/mods
RPACKS=$DIR/resourcepacks
SAVES=$DIR/saves
SPACKS=$DIR/shaderpacks
VERSIONS=$DIR/versions
##############################

## REQUIREMENTS ##############
senderr(){ echo pmcp: "$@";exit 1; }

[ -d $DIR ] || senderr portablemc dir not found
[ -z $EDITOR ] && senderr \$EDITOR not set

for SW in fzf portablemc
do
  which $SW >$N 2>&1 || senderr $SW not found
done
##############################

## MAIN ######################

config(){
  [ -d $CONFIG ] || senderr config dir not found
  case $1 in
    '') cd $CONFIG ;;
  esac
}

logs(){
  [ -d $LOGS ] || senderr config dir not found
  case $1 in
    '') cd $LOGS ;;
  esac
}

mods(){
  [ -d $MODS ] || senderr config dir not found
  case $1 in
    '') cd $MODS ;;
  esac
}

rpacks(){
  [ -d $RPACKS ] || senderr config dir not found
  case $1 in
    '') cd $CONFIG ;;
  esac
}

saves(){
  [ -d $SAVES ] || senderr config dir not found
  case $1 in
    '') cd $SAVES ;;
  esac
}

spacks(){
  [ -d $SPACKS ] || senderr config dir not found
  case $1 in
    '') cd $SAVES ;;
  esac
}

versions(){
  [ -d $VERSIONS ] || senderr config dir not found
  case $1 in
    '') cd $VERSIONS ;;
  esac
}

case $1 in
  config) config "$2" ;;
  logs) logs "$2" ;;
  mods) mods "$2" ;;
  rpacks) rpacks "$2" ;;
  saves) saves "$2" ;;
  spacks) spacks "$2" ;;
  versions) versions "$2" ;;
  *) portablemc $@ ;;
esac


}
