# Shell
#[shell]
#  program = "powershell"
#  args = ["-nologo"]

# Window
[window]
  opacity = 0.90
  padding.x = 20
  padding.y = 20

# Font
[font]
  normal.family = "HackNerdFont"

# Make Alacritty send the expected key-code
[[keyboard.bindings]]
  chars = "\u001B[13;5u"
  key = "Return"
  mods = "Control"

# TokyoNight : https://github.com/folke/tokyonight.nvim
[colors.primary]
  background = '#1a1b26'
  foreground = '#c0caf5'
[colors.cursor]
  cursor = '#c0caf5'
  text = '#1a1b26'
[colors.normal]
  black = '#15161e'
  blue = '#7aa2f7'
  cyan = '#7dcfff'
  green = '#9ece6a'
  magenta = '#bb9af7'
  red = '#f7768e'
  white = '#a9b1d6'
  yellow = '#e0af68'
[colors.bright]
  black = '#414868'
  blue = '#7aa2f7'
  cyan = '#7dcfff'
  green = '#9ece6a'
  magenta = '#bb9af7'
  red = '#f7768e'
  white = '#c0caf5'
  yellow = '#e0af68'
[[colors.indexed_colors]]
  color = '#ff9e64'
  index = 16
[[colors.indexed_colors]]
  color = '#db4b4b'
  index = 17
