[window]
  opacity = 0.80
  padding.x = 20
  padding.y = 20

[font]
  normal.family = "HackNerdFont"

#[shell]
#  program = "powershell"
#  args = ["-nologo"]

# Gotham : https://github.com/whatyouhide/vim-gotham

[colors.primary]
  background = '#0a0f14'
  foreground = '#98d1ce'
[colors.normal]
  black = '#0a0f14'
  blue = '#195465'
  cyan = '#33859d'
  green = '#26a98b'
  magenta = '#4e5165'
  red = '#c33027'
  white = '#98d1ce'
  yellow = '#edb54b'
[colors.bright]
  black = '#10151b'
  blue = '#093748'
  cyan = '#599caa'
  green = '#081f2d'
  magenta = '#888ba5'
  red = '#d26939'
  white = '#d3ebe9'
  yellow = '#245361'
